-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Počítač: 127.0.0.1
-- Vytvořeno: Pon 24. bře 2025, 00:40
-- Verze serveru: 10.4.32-MariaDB
-- Verze PHP: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Databáze: `news`
--

-- --------------------------------------------------------

--
-- Struktura tabulky `news`
--

CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `title_en` varchar(255) DEFAULT NULL,
  `content` text NOT NULL,
  `content_en` text DEFAULT NULL,
  `created_at` date DEFAULT curdate(),
  `image` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

--
-- Vypisuji data pro tabulku `news`
--

INSERT INTO `news` (`id`, `title`, `title_en`, `content`, `content_en`, `created_at`, `image`) VALUES
(1, 'Máme nová koťátka - vrh \"X\" a vrh \"Y\"', 'We have new kittens - litters \"X\" and \"Y\"', '22.11. 2024 se nám narodili 2 holky a 3 kluci ze spojení Angela Garfield\'s Baby a Kristian A Lynx Star. \r\n28.11. 2024 se nám narodila holka a 3 kluci ze spojení Katelynn Garfield\'s Baby a Kristian A Lynx Star.', 'On 22.11.2024, 2 girls and 3 boys were born from the pairing of Angela Garfield\'s Baby and Kristian A Lynx Star. \r\nOn 28.11.2024, 1 girl and 3 boys were born from the pairing of Katelynn Garfield\'s Baby and Kristian A Lynx Star.', '2025-01-10', '../img/news/vrh_x_06m.jpg, ../img/news/vrh_y_05mm.jpg'),
(2, 'Máme nová koťátka - vrh \"V\" a vrh \"W\"', 'We have new kittens - litters \"V\" and \"W\"', '21.10. 2024 se nám narodila holka a 3 kluci ze spojení Hany Garfield\'s Baby a Kristian A Lynx Star. \r\n25.10. 2024 se nám narodila holka a 3 kluci ze spojení Quella Garfield\'s Baby a Kristian A Lynx Star.', 'On 21.10.2024, 1 girl and 3 boys were born from the pairing of Hany Garfield\'s Baby and Kristian A Lynx Star. \r\nOn 25.10.2024, 1 girl and 3 boys were born from the pairing of Quella Garfield\'s Baby and Kristian A Lynx Star.', '2025-01-10', NULL),
(3, 'Máme nová koťátka - vrh \"U\"', 'We have new kittens - litter \"U\"', '12.9. 2024 se nám narodili 2 holky a kluk ze spojení Cassandra Garfield\'s Baby a Kristian A Lynx Star.', 'On 12.9.2024, 2 girls and 1 boy were born from the pairing of Cassandra Garfield\'s Baby and Kristian A Lynx Star.', '2024-11-09', NULL),
(4, 'Kristian a Lynx Star - nový krycí kocour', 'Kristian and Lynx Star - new stud cat', 'V sekci Kocouři představujeme nového krycího kocoura. Najdete zde jeho profilové fotografie včetně rodokmenu.', 'In the Studs section, we introduce a new stud cat. You can find his profile photos including his pedigree.', '2024-11-09', NULL),
(5, 'Tari a Tazen Garfield\'s Baby - poslední volná kočička a kocourek z vrhu T', 'Tari and Tazen Garfield\'s Baby - last available kitten and tomcat from litter T', 'Podívejte se na nové fotografie posledních volných koťátek z vrhu T.', 'Check out the new photos of the last available kittens from litter T.', '2024-10-02', NULL),
(6, 'Safi Garfield\'s Baby - poslední volný kocourek z vrhu S ihned k odběru', 'Safi Garfield\'s Baby - last available tomcat from litter S ready for pickup', 'Poslední volný kocourek z vrhu S ihned k odběru. Podívejte se na nové fotografie.', 'The last available tomcat from litter S is ready for pickup. Check out the new photos.', '2024-08-27', NULL),
(7, 'Máme nová koťátka - vrh \"T\"', 'We have new kittens - litter \"T\"', '31.5. 2024 se nám narodili 3 kluci a 3 holky ze spojení Katelynn Garfield\'s Baby a Yogurt Marelax Pride.', 'On 31.5.2024, 3 boys and 3 girls were born from the pairing of Katelynn Garfield\'s Baby and Yogurt Marelax Pride.', '2024-08-27', NULL),
(8, 'Máme nová koťátka - vrh \"R\" a vrh \"S\"', 'We have new kittens - litters \"R\" and \"S\"', '21.4. 2024 se nám narodili 2 kluci ze spojení Happy Agostino a Yogurt Marelax Pride. \r\n25.4. 2024 se nám narodili 3 holky a 4 kluci ze spojení Olivia Garfield\'s Baby a Yogurt Marelax Pride.', 'On 21.4.2024, 2 boys were born from the pairing of Happy Agostino and Yogurt Marelax Pride. \r\nOn 25.4.2024, 3 girls and 4 boys were born from the pairing of Olivia Garfield\'s Baby and Yogurt Marelax Pride.', '2024-06-10', NULL),
(9, 'Máme nová koťátka - vrh \"Q\"', 'We have new kittens - litter \"Q\"', '8.12. 2023 se nám narodili 4 holky a 2 kluci ze spojení Hany Garfield\'s Baby a Yogurt Marelax Pride.', 'On 8.12.2023, 4 girls and 2 boys were born from the pairing of Hany Garfield\'s Baby and Yogurt Marelax Pride.', '2024-03-18', NULL),
(10, 'Máme nová koťátka - vrh \"O\" a vrh \"P\"', 'We have new kittens - litters \"O\" and \"P\"', '13.10. 2023 se nám narodil kluk ze spojení Happy Agostino a Yogurt Marelax Pride. \r\n23.10. 2023 se nám narodili 3 holky a 6 kluků ze spojení Quella Garfield\'s Baby a Yogurt Marelax Pride.', 'On 13.10.2023, 1 boy was born from the pairing of Happy Agostino and Yogurt Marelax Pride. \r\nOn 23.10.2023, 3 girls and 6 boys were born from the pairing of Quella Garfield\'s Baby and Yogurt Marelax Pride.', '2024-01-17', NULL),
(11, 'Poslední volná kočička z vrhu L ihned k odběru!', 'Last available kitten from litter L ready for pickup!', 'Lenny Garfield\'s Baby - Poslední volná kočička z vrhu L (spojení Omarion Queen of Dan a HoneyDevil Nectarine) ihned k odběru.', 'Lenny Garfield\'s Baby - The last available kitten from litter L (from the pairing of Omarion Queen of Dan and HoneyDevil Nectarine) is ready for pickup.', '2023-11-15', NULL),
(12, 'Máme nová koťátka - vrh \"N\"', 'We have new kittens - litter \"N\"', '2.8. 2023 se nám narodili 4 holky a kluk ze spojení Pady Garfield\'s Baby a Yogurt Marelax Pride.', 'On 2.8.2023, 4 girls and 1 boy were born from the pairing of Pady Garfield\'s Baby and Yogurt Marelax Pride.', '2023-08-02', NULL),
(13, 'Kristian a Lynx Star - nový krycí kocour', 'Kristian and Lynx Star - new stud cat', 'V sekci Kocouři představujeme nového krycího kocoura. Najdete zde jeho profilové fotografie včetně rodokmenu.', 'In the Studs section, we introduce a new stud cat. You can find his profile photos including his pedigree.', '2023-09-07', '../img/toms/kristian_01.jpg'),
(14, 'Máme nová koťátka - vrh \"L\" a vrh \"M\"', 'We have new kittens - litters \"L\" and \"M\"', '7.6. 2023 se nám narodilo 6 holek a 3 kluci ze spojení Omarion Queen of Dan a HoneyDevil Nectarine. \r\n7.7. 2023 se nám narodili 4 holky a kluk ze spojení Angela Garfield\'s Baby a HoneyDevil Nectarine.', 'On 7.6.2023, 6 girls and 3 boys were born from the pairing of Omarion Queen of Dan and HoneyDevil Nectarine. \r\nOn 7.7.2023, 4 girls and 1 boy were born from the pairing of Angela Garfield\'s Baby and HoneyDevil Nectarine.', '2023-09-07', NULL),
(15, 'Poslední volný kocourek z vrhu J ihned k odběru!', 'Last available tomcat from litter J ready for pickup!', 'Jerry Garfield\'s Baby - Poslední volný kocourek z vrhu J (spojení Quella Garfield\'s Baby a Hope Garfield\'s Baby) ihned k odběru.', 'Jerry Garfield\'s Baby - The last available tomcat from litter J (from the pairing of Quella Garfield\'s Baby and Hope Garfield\'s Baby) is ready for pickup.', '2023-07-18', NULL),
(16, 'Máme nová koťátka - vrh \"I\" a vrh \"J\"', 'We have new kittens - litters \"I\" and \"J\"', '23.3. 2023 se nám narodila holka a 5 kluků ze spojení Debbie Garfield\'s Baby a Hope Garfield\'s Baby. \r\n27.3. 2023 se nám narodilo 5 holek a 3 kluci ze spojení Quella Garfield\'s Baby a Hope Garfield\'s Baby.', 'On 23.3.2023, 1 girl and 5 boys were born from the pairing of Debbie Garfield\'s Baby and Hope Garfield\'s Baby. \r\nOn 27.3.2023, 5 girls and 3 boys were born from the pairing of Quella Garfield\'s Baby and Hope Garfield\'s Baby.', '2023-06-07', NULL),
(17, 'Máme nová koťátka - vrh \"CH\", \"I\" a \"J\"', 'We have new kittens - litters \"CH\", \"I\", and \"J\"', '24.2. 2023 se nám narodilo 6 kluků ze spojení Katelynn Garfield\'s Baby a Samurai Oxymoron. \r\n23.3. 2023 se nám narodila 6 koťátek ze spojení Debbie Garfield\'s Baby a Hope Garfield\'s Baby. \r\n27.3. 2023 se nám narodilo 8 koťátek ze spojení Quella Garfield\'s Baby a Hope Garfield\'s Baby.', 'On 24.2.2023, 6 boys were born from the pairing of Katelynn Garfield\'s Baby and Samurai Oxymoron. \r\nOn 23.3.2023, 6 kittens were born from the pairing of Debbie Garfield\'s Baby and Hope Garfield\'s Baby. \r\nOn 27.3.2023, 8 kittens were born from the pairing of Quella Garfield\'s Baby and Hope Garfield\'s Baby.', '2023-04-25', NULL),
(18, 'Máme nové koťátko - vrh \"H\"', 'We have a new kitten - litter \"H\"', '12. 1. 2023 se nám narodila holka ze spojení Rachel Garfield\'s Baby a Samurai Oxymoron.', 'On 12.1.2023, 1 girl was born from the pairing of Rachel Garfield\'s Baby and Samurai Oxymoron.', '2023-03-21', NULL),
(19, 'Máme nová koťátka - vrh \"F\" a vrh \"G\"', 'We have new kittens - litters \"F\" and \"G\"', '20. 10. 2022 se nám narodili 4 holky a 4 kluci ze spojení Omarion Queen of Dan a Hope Garfield\'s Baby. \r\n21. 10. 2022 se nám narodili 2 holky a 2 kluci ze spojení Quella Garfield\'s Baby a Hope Garfield\'s Baby.', 'On 20.10.2022, 4 girls and 4 boys were born from the pairing of Omarion Queen of Dan and Hope Garfield\'s Baby. \r\nOn 21.10.2022, 2 girls and 2 boys were born from the pairing of Quella Garfield\'s Baby and Hope Garfield\'s Baby.', '2023-12-20', NULL),
(20, 'Máme nové koťátko - vrh \"E\"', 'We have a new kitten - litter \"E\"', '25. 8. 2022 se nám narodila holka ze spojení Kamey Garfield\'s Baby a HoneyDevil Nectarine.', 'On 25.8.2022, 1 girl was born from the pairing of Kamey Garfield\'s Baby and HoneyDevil Nectarine.', '2022-12-02', NULL),
(21, 'Nová chovná kočka - Omarion Queen of Dan', 'New breeding cat - Omarion Queen of Dan', 'V sekci Kočky představujeme novou chovnou kočku. Najdete zde její profilové fotografie včetně rodokmenu.', 'In the Cats section, we introduce a new breeding cat. You can find her profile photos including her pedigree.', '2022-09-16', '../img/cats/omarion_01.jpg'),
(22, 'Máme nová koťátka - vrh \"D\"', 'We have new kittens - litter \"D\"', '30. 6. 2022 se nám narodily 3 holky ze spojení Pady Garfield\'s Baby a HoneyDevil Nectarine.', 'On 30.6.2022, 3 girls were born from the pairing of Pady Garfield\'s Baby and HoneyDevil Nectarine.', '2022-09-16', NULL),
(23, 'Máme nová koťátka - vrh \"C\" - poslední dva volní kluci', 'We have new kittens - litter \"C\" - last two available tomcats', 'Nové fotografie všech koťátek z vrhu C.', 'New photos of all kittens from litter C.', '2022-08-12', NULL),
(24, 'Máme nová koťátka - vrh \"A\" a vrh \"B\"', 'We have new kittens - litters \"A\" and \"B\"', '20. 4. 2022 se nám narodili 3 holky a 3 kluci ze spojení Kisha Garfield\'s Baby a HoneyDevil Nectarine.\r\n16. 5. 2022 se nám narodila holka a 3 kluci ze spojení Cassandra Garfield\'s Baby a HoneyDevil Nectarine.', 'On 20.4.2022, 3 girls and 3 boys were born from the pairing of Kisha Garfield\'s Baby and HoneyDevil Nectarine.\r\nOn 16.5.2022, 1 girl and 3 boys were born from the pairing of Cassandra Garfield\'s Baby and HoneyDevil Nectarine.', '2022-08-12', NULL),
(25, 'Nový krycí kocour - Samurai Oxymoron', 'New stud cat - Samurai Oxymoron', 'V sekci Kocouři představujeme nového krycího kocoura. Najdete zde jeho profilové fotografie včetně rodokmenu.', 'In the Studs section, we introduce a new stud cat. You can find his profile photos including his pedigree.', '2022-08-12', '../img/toms/samurai_01.jpg'),
(26, 'Yves - poslední volný kocourek z vrhu Y', 'Yves - last available tomcat from litter Y', 'Máme posledního volného kocourka z vrhu Y. Podívejte se na nové fotografie.', 'We have the last available tomcat from litter Y. Check out the new photos.', '2022-07-19', NULL),
(27, 'Máme nová koťátka - vrh \"Z\"', 'We have new kittens - litter \"Z\"', '13. 4. 2022 se nám narodili 2 holky a 5 kluků ze spojení Angela Garfield\'s Baby a HoneyDevil Nectarine.', 'On 13.4.2022, 2 girls and 5 boys were born from the pairing of Angela Garfield\'s Baby and HoneyDevil Nectarine.', '2022-07-19', NULL),
(28, 'Nová chovná kočička - Olivia Garfield\'s Baby', 'New breeding cat - Olivia Garfield\'s Baby', 'V sekci Kočky představujeme novou chovnou kočičku. Najdete zde její profilové fotografie včetně rodokmenu.', 'In the Cats section, we introduce a new breeding cat. You can find her profile photos including her pedigree.', '2022-06-23', '../img/cats/olivia_01.jpg'),
(29, 'Fotografie nových koťátek - vrh \"Y\"', 'Photos of new kittens - litter \"Y\"', '1. 3. 2022 se nám narodila holka a 2 kluci ze spojení Kamey Garfield\'s Baby a HoneyDevil Nectarine.', 'On 1.3.2022, 1 girl and 2 boys were born from the pairing of Kamey Garfield\'s Baby and HoneyDevil Nectarine.', '2022-06-21', NULL),
(30, 'Máme nová koťátka - více informací na telefonu 603 285 744', 'We have new kittens - more information at phone 603 285 744', 'Podívejte se na naše nové koťátka. Více informací najdete na telefonu 603 285 744.', 'Check out our new kittens. For more information, call 603 285 744.', '2022-04-25', NULL),
(31, 'Máme nová koťátka - vrh \"W\" a vrh \"X\"', 'We have new kittens - litters \"W\" and \"X\"', '16. 12. 2021 se nám narodili 2 holky a 3 kluci ze spojení Debbie Garfield\'s Baby a Hope Garfield\'s Baby. \r\n2. 1. 2022 se nám narodili 2 holky a 4 kluci ze spojení Rachel Garfield\'s Baby a Hope Garfield\'s Baby.', 'On 16.12.2021, 2 girls and 3 boys were born from the pairing of Debbie Garfield\'s Baby and Hope Garfield\'s Baby. \r\nOn 2.1.2022, 2 girls and 4 boys were born from the pairing of Rachel Garfield\'s Baby and Hope Garfield\'s Baby.', '2022-03-10', NULL),
(32, 'Máme nová koťátka - vrh \"V\"', 'We have new kittens - litter \"V\"', '2. 12. 2021 se nám narodila holka a 3 kluci ze spojení Pady Garfield\'s Baby a Hope Garfield\'s Baby.', 'On 2.12.2021, 1 girl and 3 boys were born from the pairing of Pady Garfield\'s Baby and Hope Garfield\'s Baby.', '2022-01-28', NULL),
(33, 'Máme nová koťátka - vrh \"T\" a vrh \"U\"', 'We have new kittens - litters \"T\" and \"U\"', '9. 9. 2021 se nám narodili 2 holky a 5 kluků ze spojení Quella Garfield\'s Baby a Hope Garfield\'s Baby. \r\n24. 9. 2021 se nám narodili 4 holky a 2 kluci ze spojení Hany Garfield\'s Baby a Mario Noblesse A Lynx Star.', 'On 9.9.2021, 2 girls and 5 boys were born from the pairing of Quella Garfield\'s Baby and Hope Garfield\'s Baby. \r\nOn 24.9.2021, 4 girls and 2 boys were born from the pairing of Hany Garfield\'s Baby and Mario Noblesse A Lynx Star.', '2021-12-08', NULL),
(34, 'Máme nová koťátka - vrh \"R\" a vrh \"S\"', 'We have new kittens - litters \"R\" and \"S\"', '27. 7. 2021 se nám narodila holka a 3 kluci ze spojení Rachel Garfield\'s Baby a Mario Noblesse A Lynx Star. \r\n1. 8. 2021 se nám narodili 3 holky a 3 kluci ze spojení Katelynn Garfield\'s Baby a Mario Noblesse A Lynx Star.', 'On 27.7.2021, 1 girl and 3 boys were born from the pairing of Rachel Garfield\'s Baby and Mario Noblesse A Lynx Star. \r\nOn 1.8.2021, 3 girls and 3 boys were born from the pairing of Katelynn Garfield\'s Baby and Mario Noblesse A Lynx Star.', '2021-10-20', NULL),
(35, 'Máme nová koťátka - vrh \"Q\"', 'We have new kittens - litter \"Q\"', '12. 6. 2021 se nám narodili 2 holky a 3 kluci ze spojení Angela Garfield\'s Baby a HoneyDevil Nectarine.', 'On 12.6.2021, 2 girls and 3 boys were born from the pairing of Angela Garfield\'s Baby and HoneyDevil Nectarine.', '2021-10-13', NULL),
(36, 'Představujeme novou chovnou kočičku - Angela Garfield\'s Baby', 'Introducing a new breeding cat - Angela Garfield\'s Baby', 'Aktuální fotografie Angely včetně rodokmenu najdete v sekci Kočky.', 'Current photos of Angela including her pedigree can be found in the Cats section.', '2021-08-09', NULL),
(37, 'Máme nová koťátka - vrh \"N\" a vrh \"O\"', 'We have new kittens - litters \"N\" and \"O\"', '24. 5. 2021 se nám narodili 2 holky a kluk ze spojení Pady Garfield\'s Baby a HoneyDevil Nectarine. \r\n25. 5. 2021 se nám narodila holka a 4 kluci ze spojení Rebeka Garfield\'s Baby a HoneyDevil Nectarine.', 'On 24.5.2021, 2 girls and 1 boy were born from the pairing of Pady Garfield\'s Baby and HoneyDevil Nectarine. \r\nOn 25.5.2021, 1 girl and 4 boys were born from the pairing of Rebeka Garfield\'s Baby and HoneyDevil Nectarine.', '2021-08-09', NULL),
(38, 'Máme nová koťátka - vrh \"P\"', 'We have new kittens - litter \"P\"', '10. 6. 2021 se nám narodili 3 holky a kluk ze spojení Happy Agostino a HoneyDevil Nectarine.', 'On 10.6.2021, 3 girls and 1 boy were born from the pairing of Happy Agostino and HoneyDevil Nectarine.', '2021-06-14', NULL),
(39, 'Máme nová koťátka - vrh \"L\" a vrh \"M\"', 'We have new kittens - litters \"L\" and \"M\"', '26. 1. 2021 se nám narodili 2 holky a 4 kluci ze spojení Ellen A Lynx Star a HoneyDevil Nectarine. \r\n1. 2. 2021 se nám narodili 2 holky a 5 kluků ze spojení Quella Garfield\'s Baby a HoneyDevil Nectarine.', 'On 26.1.2021, 2 girls and 4 boys were born from the pairing of Ellen A Lynx Star and HoneyDevil Nectarine. \r\nOn 1.2.2021, 2 girls and 5 boys were born from the pairing of Quella Garfield\'s Baby and HoneyDevil Nectarine.', '2021-05-14', NULL),
(40, 'Máme nová koťátka - vrh \"K\"', 'We have new kittens - litter \"K\"', '16. 12. 2020 se nám narodilo 5 holek a 2 kluci ze spojení Rachel Garfield\'s Baby a HoneyDevil Nectarine.', 'On 16.12.2020, 5 girls and 2 boys were born from the pairing of Rachel Garfield\'s Baby and HoneyDevil Nectarine.', '2021-02-03', NULL),
(41, 'Máme nová koťátka - vrh \"I\" a vrh \"J\"', 'We have new kittens - litters \"I\" and \"J\"', '26. 8. 2020 se nám narodili 3 holky a 3 kluci ze spojení Cassandra Garfield\'s Baby a Zucchero A Lynx Star. \r\n23. 9. 2020 se nám narodil kluk ze spojení Quella Garfield\'s Baby a HoneyDevil Nectarine.', 'On 26.8.2020, 3 girls and 3 boys were born from the pairing of Cassandra Garfield\'s Baby and Zucchero A Lynx Star. \r\nOn 23.9.2020, 1 boy was born from the pairing of Quella Garfield\'s Baby and HoneyDevil Nectarine.', '2021-02-03', NULL),
(42, 'Máme nová koťátka - vrh \"H\"', 'We have new kittens - litter \"H\"', '8. 8. 2020 se nám narodila holka a 3 kluci ze spojení Happy Agostino a Zucchero A Lynx Star.', 'On 8.8.2020, 1 girl and 3 boys were born from the pairing of Happy Agostino and Zucchero A Lynx Star.', '2020-10-20', NULL),
(43, 'Máme nová koťátka - vrh \"CH\"', 'We have new kittens - litter \"CH\"', '10. 8. 2020 se nám narodilo 5 holek a 4 kluci ze spojení Kisha Garfield\'s Baby a Zucchero A Lynx Star.', 'On 10.8.2020, 5 girls and 4 boys were born from the pairing of Kisha Garfield\'s Baby and Zucchero A Lynx Star.', '2020-10-20', NULL),
(44, 'Máme nová koťátka - vrh \"F\"', 'We have new kittens - litter \"F\"', '24. 6. 2020 se nám narodili 3 holky a 3 kluci ze spojení Debbie Garfield\'s Baby a Zucchero A Lynx Star.', 'On 24.6.2020, 3 girls and 3 boys were born from the pairing of Debbie Garfield\'s Baby and Zucchero A Lynx Star.', '2020-10-05', NULL),
(45, 'Máme nová koťátka - vrh \"G\"', 'We have new kittens - litter \"G\"', '25. 6. 2020 se nám narodil kocourek Gabro ze spojení Hany Garfield\'s Baby a Zucchero A Lynx Star.', 'On 25.6.2020, 1 tomcat named Gabro was born from the pairing of Hany Garfield\'s Baby and Zucchero A Lynx Star.', '2020-10-05', NULL),
(46, 'Nová chovná kočička - Hany Garfield\'s Baby', 'New breeding cat - Hany Garfield\'s Baby', 'V sekci Kočky představujeme novou chovnou kočičku. Najdete zde její profilové fotografie včetně rodokmenu.', 'In the Cats section, we introduce a new breeding cat. You can find her profile photos including her pedigree.', '2020-10-05', '../img/cats/hany_01.jpg'),
(47, 'Máme nová koťátka - vrh \"D\"', 'We have new kittens - litter \"D\"', '17. 4. 2020 se nám narodila holka a 4 kluci ze spojení Katelynn Garfield\'s Baby a Zucchero A Lynx Star.', 'On 17.4.2020, 1 girl and 4 boys were born from the pairing of Katelynn Garfield\'s Baby and Zucchero A Lynx Star.', '2020-06-26', NULL),
(48, 'Máme nová koťátka - vrh \"E\"', 'We have new kittens - litter \"E\"', '3. 5. 2020 se nám narodili 4 holky a 3 kluci ze spojení Rebeka Garfield\'s Baby a Zucchero A Lynx Star.', 'On 3.5.2020, 4 girls and 3 boys were born from the pairing of Rebeka Garfield\'s Baby and Zucchero A Lynx Star.', '2020-06-26', NULL),
(49, 'Nová chovná kočička - Katelynn Garfield\'s Baby', 'New breeding cat - Katelynn Garfield\'s Baby', 'V sekci Kočky představujeme novou chovnou kočičku. Najdete zde její profilové fotografie včetně rodokmenu.', 'In the Cats section, we introduce a new breeding cat. You can find her profile photos including her pedigree.', '2020-06-26', '../img/cats/katelynn_01.jpg'),
(50, 'Máme nová koťátka - vrh \"C\"', 'We have new kittens - litter \"C\"', '3. 3. 2020 se nám narodili 2 holky a 3 kluci ze spojení Kamey Garfield\'s Baby a Zucchero A Lynx Star.', 'On 3.3.2020, 2 girls and 3 boys were born from the pairing of Kamey Garfield\'s Baby and Zucchero A Lynx Star.', '2020-05-05', NULL),
(51, 'Nové fotografie koťátek z vrhu \"B\"', 'New photos of kittens from litter \"B\"', 'Do sekce Odchovy jsme přesunuli koťátka z vrhu B a doplnili jejich aktuální fotografie.', 'We have moved the kittens from litter B to the Litters section and added their current photos.', '2020-03-25', NULL),
(52, 'Máme nová koťátka - vrh \"B\"', 'We have new kittens - litter \"B\"', '9. 2. 2020 se nám narodili 2 holky a 3 kluci ze spojení Pady Garfield\'s Baby a Zucchero A Lynx Star.', 'On 9.2.2020, 2 girls and 3 boys were born from the pairing of Pady Garfield\'s Baby and Zucchero A Lynx Star.', '2020-03-02', NULL),
(53, 'Zora Garfield\'s Baby - poslední volná kočička z vrhu \"Z\"', 'Zora Garfield\'s Baby - last available kitten from litter \"Z\"', 'Máme nová koťátka - vrh \"Z\". 20. 11. 2019 se nám narodili 4 holky a 2 kluci ze spojení Mauglina Garfield\'s Baby a Zucchero A Lynx Star.', 'We have new kittens - litter \"Z\". On 20.11.2019, 4 girls and 2 boys were born from the pairing of Mauglina Garfield\'s Baby and Zucchero A Lynx Star.', '2020-03-02', NULL),
(54, 'Máme nová koťátka - vrh \"A\"', 'We have new kittens - litter \"A\"', '22. 11. 2019 se nám narodili 4 holky a kluk ze spojení Kisha Garfield\'s Baby a Zucchero A Lynx Star.', 'On 22.11.2019, 4 girls and 1 boy were born from the pairing of Kisha Garfield\'s Baby and Zucchero A Lynx Star.', '2020-03-02', NULL),
(55, 'Máme nová koťátka - vrh \"Y\"', 'We have new kittens - litter \"Y\"', '4. listopadu 2019 se nám narodili 2 holčičky a 2 kluci ze spojení Ellen A Lynx Star a Zucchero A Lynx Star.', 'On 4.11.2019, 2 girls and 2 boys were born from the pairing of Ellen A Lynx Star and Zucchero A Lynx Star.', '2020-01-31', NULL),
(56, 'Máme nová koťátka - vrh \"X\"', 'We have new kittens - litter \"X\"', '27. října 2019 se nám narodili 2 holčičky a 2 kluci ze spojení Queeny Bella A Lynx Star a Loki Blue Laguna Leo.', 'On 27.10.2019, 2 girls and 2 boys were born from the pairing of Queeny Bella A Lynx Star and Loki Blue Laguna Leo.', '2020-01-16', NULL),
(57, 'Máme nová koťátka - vrh \"W\"', 'We have new kittens - litter \"W\"', '22. října 2019 se nám narodili 3 holčičky a 2 kluci ze spojení Elis Garfield\'s Baby a Zucchero A Lynx Star.', 'On 22.10.2019, 3 girls and 2 boys were born from the pairing of Elis Garfield\'s Baby and Zucchero A Lynx Star.', '2019-12-16', NULL),
(58, 'Máme nová koťátka - vrh \"V\"', 'We have new kittens - litter \"V\"', '23. září 2019 se nám narodila holčička a 3 kluci ze spojení Cassandra Garfield\'s Baby a Zucchero A Lynx Star.', 'On 23.9.2019, 1 girl and 3 boys were born from the pairing of Cassandra Garfield\'s Baby and Zucchero A Lynx Star.', '2019-11-04', NULL),
(59, 'Máme nová koťátka - vrh \"U\"', 'We have new kittens - litter \"U\"', '23. července 2019 se nám narodila holčička a kluk ze spojení Rebeka Garfield\'s Baby a Zucchero A Lynx Star.', 'On 23.7.2019, 1 girl and 1 boy were born from the pairing of Rebeka Garfield\'s Baby and Zucchero A Lynx Star.', '2019-10-24', NULL),
(60, 'Máme nová koťátka - vrh \"T\"', 'We have new kittens - litter \"T\"', '30. dubna 2019 se nám narodili tři holčičky a dva kluci ze spojení Ornela Garfield\'s Baby a Lukas Baccarcoon.', 'On 30.4.2019, 3 girls and 2 boys were born from the pairing of Ornela Garfield\'s Baby and Lukas Baccarcoon.', '2019-09-17', NULL),
(61, 'Nový krycí kocour - Zucchero A Lynx Star', 'New stud cat - Zucchero A Lynx Star', 'Do sekce Kocouři jsme přidali nového krycího kocoura. Najdete zde jeho profilové fotografie včetně rodokmenu.', 'In the Studs section, we introduce a new stud cat. You can find his profile photos including his pedigree.', '2019-06-19', '../img/castrates/zucchero_01.jpg'),
(62, 'Máme nová koťátka - vrh \"R\"', 'We have new kittens - litter \"R\"', '11. dubna 2019 se nám narodili dvě holčičky a dva kluci ze spojení Cassandra Garfield\'s Baby a Lukas Baccarcoon.', 'On 11.4.2019, 2 girls and 2 boys were born from the pairing of Cassandra Garfield\'s Baby and Lukas Baccarcoon.', '2019-06-19', NULL),
(63, 'Máme nová koťátka - vrh \"S\"', 'We have new kittens - litter \"S\"', '15. dubna 2019 se nám narodili dvě holky a dva kluci ze spojení Debbie Garfield\'s Baby a Lukas Baccarcoon.', 'On 15.4.2019, 2 girls and 2 boys were born from the pairing of Debbie Garfield\'s Baby and Lukas Baccarcoon.', '2019-06-19', NULL),
(64, 'Nová chovná kočička - Cassandra Garfield\'s Baby', 'New breeding cat - Cassandra Garfield\'s Baby', 'Do sekce Kočky jsme přidali Cassandru Garfield\'s Baby.', 'In the Cats section, we introduce Cassandra Garfield\'s Baby.', '2019-06-19', '../img/cats/cassandra_01.jpg'),
(65, 'Máme nová koťátka - vrh \"Q\"', 'We have new kittens - litter \"Q\"', '14. 3. 2019 se nám narodili 3 holčičky a 2 kluci ze spojení Mauglina Garfield\'s Baby a Lukas Baccarcoon.', 'On 14.3.2019, 3 girls and 2 boys were born from the pairing of Mauglina Garfield\'s Baby and Lukas Baccarcoon.', '2019-05-16', NULL),
(66, 'Máme nová koťátka - vrh \"P\"', 'We have new kittens - litter \"P\"', '2. 2. 2019 se nám narodila holčička a kluk ze spojení Happy Agostino a Lukas Baccarcoon.', 'On 2.2.2019, 1 girl and 1 boy were born from the pairing of Happy Agostino and Lukas Baccarcoon.', '2019-04-03', NULL),
(67, 'Představujeme dvě nové chovné kočičky', 'Introducing two new breeding cats', 'Jejich aktuální fotografie najdete v sekci Kočky.', 'You can find their current photos in the Cats section.', '2019-02-03', '../img/cats/debbie_01.jpg, ../img/castrates/elis_01.jpg'),
(68, 'Máme nová koťátka - vrh \"O\"', 'We have new kittens - litter \"O\"', '10. 12. 2018 se nám narodila holčička a 2 kluci ze spojení Schery Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 10.12.2018, 1 girl and 2 boys were born from the pairing of Schery Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-12-10', NULL),
(69, 'Máme nová koťátka - vrhy \"M\" a \"N\"', 'We have new kittens - litters \"M\" and \"N\"', 'VRH \"M\" 21. 10. 2018 se nám narodili 3 holky a 4 kluci ze spojení Rebeka Garfield\'s Baby a Lukas Baccaracoon. VRH \"N\" 10. 11. 2018 se nám narodili 2 holky a 3 kluci ze spojení Ellen A Lynx Star a Lukas Baccarcoon.', 'Litter \"M\" - On 21.10.2018, 3 girls and 4 boys were born from the pairing of Rebeka Garfield\'s Baby and Lukas Baccaracoon. Litter \"N\" - On 10.11.2018, 2 girls and 3 boys were born from the pairing of Ellen A Lynx Star and Lukas Baccarcoon.', '2018-12-06', NULL),
(70, 'Joana Garfield\'s Baby - ihned k odběru!', 'Joana Garfield\'s Baby - ready for pickup!', 'Poslední volná kočička z vrhu J ihned k odběru. Podívejte se na její aktuální fotografie.', 'The last available kitten from litter J is ready for pickup. Check out her current photos.', '2018-12-06', NULL),
(71, 'Máme nová koťátka - vrhy \"K\" a \"L\"', 'We have new kittens - litters \"K\" and \"L\"', 'VRH \"K\" 18. 8. 2018 se nám narodili 2 holky a 3 kluci ze spojení Kamey Garfield\'s Baby a Loki Blue Laguna Leo. VRH \"L\" 30. 8. 2018 se nám narodili 4 holky a 2 kluci ze spojení Pady Garfield\'s Baby a Loki Blue Laguna Leo.', 'Litter \"K\" - On 18.8.2018, 2 girls and 3 boys were born from the pairing of Kamey Garfield\'s Baby and Loki Blue Laguna Leo. Litter \"L\" - On 30.8.2018, 4 girls and 2 boys were born from the pairing of Pady Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-11-08', NULL),
(72, 'Máme nová koťátka - vrhy \"I\" a \"J\"', 'We have new kittens - litters \"I\" and \"J\"', 'VRH \"I\" 13. 8. 2018 se nám narodili 3 kluci ze spojení Mauglina Garfield\'s Baby a Jason Agostino. VRH \"J\" 17. 8. 2018 se nám narodili 2 holčičky a kluk ze spojení Osiris Garfield\'s Baby a Jason Agostino.', 'Litter \"I\" - On 13.8.2018, 3 boys were born from the pairing of Mauglina Garfield\'s Baby and Jason Agostino. Litter \"J\" - On 17.8.2018, 2 girls and 1 boy were born from the pairing of Osiris Garfield\'s Baby and Jason Agostino.', '2018-09-07', NULL),
(73, 'Nová chovná kočička - Kamey Garfield\'s Baby', 'New breeding cat - Kamey Garfield\'s Baby', 'Profilové fotografie naleznete v sekci Kočky.', 'Profile photos can be found in the Cats section.', '2018-09-07', '../img/cats/kamey_01.jpg'),
(74, 'Máme nová koťátka - vrh \"H\"', 'We have new kittens - litter \"H\"', '5. 7. 2018 se nám narodila holčička a 4 kluci ze spojení Happy Agostino a Loki Blue Laguna Leo.', 'On 5.7.2018, 1 girl and 4 boys were born from the pairing of Happy Agostino and Loki Blue Laguna Leo.', '2018-07-05', NULL),
(75, 'Máme nová koťátka - vrh \"CH\"', 'We have new kittens - litter \"CH\"', '18. 7. 2018 se nám narodili 2 holčičky a 4 kluci ze spojení CH Emphaty Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 18.7.2018, 2 girls and 4 boys were born from the pairing of CH Emphaty Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-07-18', NULL),
(76, 'Máme nová koťátka - vrh \"F\"', 'We have new kittens - litter \"F\"', '9. 4. 2018 se nám narodily dvě holčičky a tři kluci ze spojení Kisha Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 9.4.2018, 2 girls and 3 boys were born from the pairing of Kisha Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-06-18', NULL),
(77, 'Máme nová koťátka - vrh \"G\"', 'We have new kittens - litter \"G\"', '16. 4. 2018 se nám narodili dva kluci ze spojení Schery Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 16.4.2018, 2 boys were born from the pairing of Schery Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-06-18', NULL),
(78, 'Nová chovná kočička - Schery Garfield\'s Baby', 'New breeding cat - Schery Garfield\'s Baby', 'Do sekce Kočky jsme přidali Schery Garfield\'s Baby.', 'In the Cats section, we introduce Schery Garfield\'s Baby.', '2018-06-18', '../img/castrates/schery_01.jpg'),
(79, 'Nové fotografie koťátek z vrhu \"D\" a \"E\" - 12 týdnů', 'New photos of kittens from litters \"D\" and \"E\" - 12 weeks', '12. 5. 2018.', '12.5.2018.', '2018-05-16', NULL),
(80, 'Nové fotografie koťátek z vrhu \"D\" a \"E\" - 8 týdnů', 'New photos of kittens from litters \"D\" and \"E\" - 8 weeks', '13. 4. 2018.', '13.4.2018.', '2018-04-13', NULL),
(81, 'Máme nová koťátka - vrh \"D\"', 'We have new kittens - litter \"D\"', '10. 2. 2018 se nám narodila holčička a pět kluků ze spojení Queeny Bella A Lynx Star a Loki Blue Laguna Leo.', 'On 10.2.2018, 1 girl and 5 boys were born from the pairing of Queeny Bella A Lynx Star and Loki Blue Laguna Leo.', '2018-03-23', NULL),
(82, 'Máme nová koťátka - vrh \"E\"', 'We have new kittens - litter \"E\"', '12. 2. 2018 se nám narodila holčička a kluk ze spojení Rebeka Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 12.2.2018, 1 girl and 1 boy were born from the pairing of Rebeka Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-03-23', NULL),
(83, 'Máme nová koťátka - vrh \"C\"', 'We have new kittens - litter \"C\"', '6. 12. 2017 se nám narodila holčička a kluk ze spojení Kisha Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 6.12.2017, 1 girl and 1 boy were born from the pairing of Kisha Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-03-13', NULL),
(84, 'Máme nová koťátka - vrh \"B\"', 'We have new kittens - litter \"B\"', '18. 11. 2017 se nám narodili čtyři holčičky ze spojení Mauglina Garfield\'s Baby a Loki Blue Laguna Leo.', 'On 18.11.2017, 4 girls were born from the pairing of Mauglina Garfield\'s Baby and Loki Blue Laguna Leo.', '2018-01-31', NULL),
(85, 'Máme nová koťátka - vrh \"A\"', 'We have new kittens - litter \"A\"', '29. 10. 2017 se nám narodili tři holčičky a kluk ze spojení Happy Agostino a Chopper Garfield\'s Baby.', 'On 29.10.2017, 3 girls and 1 boy were born from the pairing of Happy Agostino and Chopper Garfield\'s Baby.', '2018-01-17', NULL),
(86, 'Máme nová koťátka - vrh \"Z\"', 'We have new kittens - litter \"Z\"', '9. 10. 2017 se nám narodili 2 kočičky a 2 kocourci ze spojení Queeny Bella A Lynx Star a Chopper Garfield\'s Baby.', 'On 9.10.2017, 2 girls and 2 boys were born from the pairing of Queeny Bella A Lynx Star and Chopper Garfield\'s Baby.', '2018-01-10', NULL),
(87, 'Máme nová koťátka - vrh \"Y\"', 'We have new kittens - litter \"Y\"', '3. září 2017 se nám narodili 3 kočičky a 4 kocourci ze spojení CH Emphaty Garfield\'s Baby a Chopper Garfield\'s Baby. Více informací jako vždy v sekci Koťátka', 'On 3.9.2017, 3 girls and 4 boys were born from the pairing of CH Emphaty Garfield\'s Baby and Chopper Garfield\'s Baby. More information as always in the Kittens section.', '2017-11-03', NULL),
(88, 'Představujeme dvě nové chovné kočičky', 'Introducing two new breeding cats', 'V sekci Kočky najdete dvě nové chovné kočičky, jejich aktuální fotografie i rodokmeny.', 'In the Cats section, you can find two new breeding cats, their current photos, and pedigrees.', '2017-10-30', '../img/cats/pady_01.jpg, ../img/cats/happy_01.jpg'),
(89, 'Představujeme nová koťátka - vrh \"X\"', 'Introducing new kittens - litter \"X\"', '12. června 2017 se nám narodili 2 kočičky a kocourek ze spojení Osiris Garfield\'s Baby a Chopper Garfield\'s Baby.', 'On 12.6.2017, 2 girls and 1 boy were born from the pairing of Osiris Garfield\'s Baby and Chopper Garfield\'s Baby.', '2017-09-05', NULL),
(90, 'Máme nová koťátka - vrhy \"V\" a \"W\"', 'We have new kittens - litters \"V\" and \"W\"', 'Představujeme nová koťátka z obou aktuálních vrhů V a W. Podívejte se první fotografie jako vždy v sekci Koťátka.', 'Introducing new kittens from both current litters V and W. Check out the first photos as always in the Kittens section.', '2017-06-30', NULL),
(91, 'Profilové fotky krycího kocoura Lokiho', 'Profile photos of stud cat Loki', 'Profilové fotky krycího kocoura Lokiho včetně rodokmenu v sekci Kocouři.', 'Profile photos of stud cat Loki including his pedigree in the Studs section.', '2017-06-30', '../img/castrates/loki_01.jpg'),
(92, 'Rachel Garfield\'s Baby - ihned k odběru!', 'Rachel Garfield\'s Baby - ready for pickup!', 'Poslední volná kočička z vrhu R ihned k odběru. Podívejte se na její aktuální fotografie v sekci Odchovy.', 'The last available kitten from litter R is ready for pickup. Check out her current photos in the Litters section.', '2017-05-11', NULL),
(93, 'Máme nová koťátka - vrhy \"T\" a \"U\"', 'We have new kittens - litters \"T\" and \"U\"', 'Představujeme nová koťátka z obou aktuálních vrhů T a U. Podívejte se první fotografie jako vždy v sekci Koťátka.', 'Introducing new kittens from both current litters T and U. Check out the first photos as always in the Kittens section.', '2017-05-11', NULL),
(94, 'Máme nová koťátka - Vrh S', 'We have new kittens - litter S', 'Představujeme nový vrh koťátek - vrh S. Tři kluci a čtyři holky se narodili 30. prosince 2016 ze spojení CH Emphaty Garfield\'s Baby a Chopper Garfield\'s Baby. Podívejte se na jejich první fotografie.', 'Introducing a new litter of kittens - litter S. Three boys and four girls were born on 30.12.2016 from the pairing of CH Emphaty Garfield\'s Baby and Chopper Garfield\'s Baby. Check out their first photos.', '2017-03-10', NULL),
(95, 'Představujeme nové chovné kočičky', 'Introducing new breeding cats', 'Do sekce Kočky jsme přidali dvě nové chovné kočičky. Najdete zde jejich aktuální fotografie včetně rodokmenu.', 'In the Cats section, we have added two new breeding cats. You can find their current photos including pedigrees.', '2017-03-03', '../img/cats/kisha_01.jpg, ../img/castrates/queeny_01.jpg'),
(96, 'Máme nová koťátka - Vrh R', 'We have new kittens - litter R', 'Představujeme nový vrh koťátka - vrh R. Tři kluci a jedna holka se narodili 20. prosince 2016 ze spojení Ornela Garfield\'s Baby a Mainefield\'s Harvey. Podívejte se na jejich první fotografie.', 'Introducing a new litter of kittens - litter R. Three boys and one girl were born on 20.12.2016 from the pairing of Ornela Garfield\'s Baby and Mainefield\'s Harvey. Check out their first photos.', '2017-02-14', '../img/news/vrh_r_06.jpg'),
(97, 'Vrh Q - nové fotografie a poslední volná kočička', 'Litter Q - new photos and last available kitten', 'Máme poslední volnou kočičku Quadis z vrhu Q. Podívejte se na aktuální fotografie do sekce Koťátka.', 'We have the last available kitten Quadis from litter Q. Check out the current photos in the Kittens section.', '2017-02-10', NULL),
(98, 'Vyhledávač koťátek :)', 'Kitten search :)', 'Zajímá vás jak vypadají koťátka konkrétní barvy? Vyzkoušejte náš vyhledávač koťátek :) Stačí zadat kód barvy a hned se Vám zobrazí veškeré informace o všech našich koťátkách v této barvě.', 'Are you interested in what kittens of a specific color look like? Try our kitten search :) Just enter the color code and you will immediately see all the information about all our kittens in this color.', '2017-01-30', NULL),
(99, 'Máme nová koťátka - vrh Q', 'We have new kittens - litter Q', '11. listopadu 2016 se nám narodili 2 kočičky a 3 kocourci ze spojení Ellen A Lynx Star a Lukas Baccaracoon. Podívejte se na jejich první fotografie.', 'On 11.11.2016, 2 girls and 3 boys were born from the pairing of Ellen A Lynx Star and Lukas Baccaracoon. Check out their first photos.', '2017-01-17', '../img/news/vrh_q_08mm.jpg'),
(100, 'Představujeme nové krycí kocoury', 'Introducing new stud cats', 'Vítáme Choppera a Lokiho do naší kočičí rodiny a představujeme jejich první fotografie.', 'We welcome Chopper and Loki to our cat family and present their first photos.', '2016-11-28', '../img/castrates/chopper_01.jpg, ../img/castrates/loki_01.jpg'),
(101, 'Máme nová koťátka - vrh P', 'We have new kittens - litter P', '21. září 2016 se nám narodilo 5 kočiček a 4 kocourci ze spojení Rebeka Garfield\'s Baby a Chopper Garfield\'s Baby. Podívejte se na jejich první fotografie.', 'On 21.9.2016, 5 girls and 4 boys were born from the pairing of Rebeka Garfield\'s Baby and Chopper Garfield\'s Baby. Check out their first photos.', '2016-11-21', NULL),
(102, 'Těšte se na první fotografie nového vrhu P - již příští týden', 'Look forward to the first photos of the new litter P - next week', 'Koťátka z vrhu \"N\" byly přesunuty do Odchovů.', 'Kittens from litter \"N\" have been moved to the Litters section.', '2016-11-11', NULL),
(103, 'Máme nová koťátka - vrh O', 'We have new kittens - litter O', '31. srpna 2016 se nám narodili 2 kočičky a kocourek ze spojení CH Arka Garfield\'s Baby a Lukas Baccaracoon. Podívejte se na jejich první fotografie.', 'On 31.8.2016, 2 girls and 1 boy were born from the pairing of CH Arka Garfield\'s Baby and Lukas Baccaracoon. Check out their first photos.', '2016-10-21', NULL),
(104, 'Koťátka - vrh N - ihned k odběru!', 'Kittens - litter N - ready for pickup!', 'Poslední dvě volné kočičky z vrhu N jsou ihned k odběru.', 'The last two available kittens from litter N are ready for pickup.', '2016-10-21', NULL),
(105, 'Máme nová koťátka - vrh N', 'We have new kittens - litter N', '18. července 2016 se nám narodili 2 kočičky a 5 kocourků. Podívejte se na jejich první fotografie.', 'On 18.7.2016, 2 girls and 5 boys were born. Check out their first photos.', '2016-09-20', NULL),
(106, 'Představujeme koťátka z vrhů L a M', 'Introducing kittens from litters L and M', '', '', '2016-08-19', NULL),
(107, 'Nové fotografie koťátek z obou aktuálních vrhů J a K', 'New photos of kittens from both current litters J and K', '', '', '2016-03-15', NULL),
(108, 'Kde všude jsou naše koťátka?', 'Where are our kittens?', 'Do sekce \"O nás\" jsme přidali mapku zemí, ve kterých už jsou naše koťátka a doufáme, že jí budeme s Vaší pomocí nadále rozšiřovat :)', 'In the \"About Us\" section, we have added a map of countries where our kittens are already located, and we hope to expand it further with your help :)', '2016-02-23', '../img/news/map.jpg'),
(109, 'Máme nová koťátka ... - vrh J', 'We have new kittens ... - litter J', 'Představujeme nová koťátka z vrhu J. 2 holčičky a 2 kluci se narodili 21.12.2015 ze spojení CH Arka Garfield\'s Baby a Lukas Baccaracoon.', 'Introducing new kittens from litter J. 2 girls and 2 boys were born on 21.12.2015 from the pairing of CH Arka Garfield\'s Baby and Lukas Baccaracoon.', '2016-02-15', NULL),
(110, '... a hned dva vrhy :) - vrh K', '... and two litters :) - litter K', 'Představujeme nová koťátka z vrhu K. Narodila se o dva týdny déle než jejich kamarádi z vrhu J a je jim tedy 6 týdnů :)', 'Introducing new kittens from litter K. They were born two weeks later than their friends from litter J and are now 6 weeks old :)', '2016-02-15', NULL),
(111, 'DĚKUJEME VÁM ZA PŘÍZEŇ V UPLYNULÉM ROCE A PŘEJEM VŠE NEJLEPŠÍ A SPOUSTU KRÁSNÝCH ZÁŽITKŮ S VAŠIMI MAZLÍČKY V ROCE 2016! :O)', 'THANK YOU FOR YOUR SUPPORT IN THE PAST YEAR AND WISH YOU ALL THE BEST AND LOTS OF WONDERFUL MOMENTS WITH YOUR PETS IN 2016! :O)', '', '', '2016-01-09', NULL),
(112, 'Nové fotografie koťátek z vrhu CH', 'New photos of kittens from litter CH', 'Podívejte se jak rostou :o) Už je jim 11 týdnů za nedlouho se vydají do svých nových domovů...', 'See how they grow :o) They are already 11 weeks old and will soon go to their new homes...', '2015-12-04', NULL),
(113, 'Máme nová koťátka :) - vrh I', 'We have new kittens :) - litter I', 'Představujeme nová koťátka z vrhu I. 3 holčičky a 2 kluci se narodili 24.10.2015 ze spojení Osiris Garfield\'s Baby a Lukas Baccaracoon.', 'Introducing new kittens from litter I. 3 girls and 2 boys were born on 24.10.2015 from the pairing of Osiris Garfield\'s Baby and Lukas Baccaracoon.', '2015-12-04', NULL),
(114, 'Nové fotografie koťátek z vrhu CH', 'New photos of kittens from litter CH', 'A je to tu :) Nové fotografie koťátek z vrhu CH najdete v sekci Koťátka.', 'Here it is :) New photos of kittens from litter CH can be found in the Kittens section.', '2015-11-20', NULL),
(115, 'Koťátka - vrh CH', 'Kittens - litter CH', 'Těšte se na nové fotografie koťátek z vrhu CH, již brzy na našich stránkách :) Vrh H přesunut do Odchovů.', 'Look forward to new photos of kittens from litter CH, coming soon to our website :) Litter H has been moved to the Litters section.', '2015-11-04', NULL),
(116, 'Hurricane - poslední volný kocourek z vrhu H', 'Hurricane - last available tomcat from litter H', 'Máme posledního volného kocourka z vrhu H. Podívejte se na nové fotografie.', 'We have the last available tomcat from litter H. Check out the new photos.', '2015-10-19', NULL),
(117, 'Máme nová koťátka - vrh CH', 'We have new kittens - litter CH', 'Představujeme nová koťátka z vrhu CH. Tři kluci Chicco, Chopper a Chuck se narodili 14. září a už se na Vás těší :)', 'Introducing new kittens from litter CH. Three boys Chicco, Chopper, and Chuck were born on 14.9 and are already looking forward to seeing you :)', '2015-09-30', NULL),
(118, 'Nové fotografie koťátek z vrhu H', 'New photos of kittens from litter H', 'Vrh G přesunut do Odchovů.', 'Litter G has been moved to the Litters section.', '2015-08-21', NULL),
(119, 'Máme dva nové vrhy G a H', 'We have two new litters G and H', 'Goldie, kočička z vrhu G se narodila 24. 5. 2015. Henk, Huckleberry a Hurricane, 3 kluci z vrhu H, se narodili 25. 7. 2015.', 'Goldie, a kitten from litter G, was born on 24.5.2015. Henk, Huckleberry, and Hurricane, 3 boys from litter H, were born on 25.7.2015.', '2015-08-21', NULL),
(120, 'Eminem - poslední volný kocourek z vrhu E', 'Eminem - last available tomcat from litter E', 'Máme posledního volného kocourka z vrhu E. Podívejte se na jeho 15-týdenní fotografie v sekci Koťátka', 'We have the last available tomcat from litter E. Check out his 15-week photos in the Kittens section.', '2015-07-14', NULL),
(121, 'Máme nové koťátko - Fantasy - vrh F', 'We have a new kitten - Fantasy - litter F', 'První fotografie Fantasy najdete v sekci Koťátka', 'First photos of Fantasy can be found in the Kittens section.', '2015-07-14', NULL),
(122, 'Nové fotografie koťátek- vrh E', 'New photos of kittens - litter E', 'Podívejte se na nové fotografie našich 10-týdenních koťátek z vrhu E.\\nKoťátka z vrhu D přesunuta do Odchovů.', 'Check out the new photos of our 10-week-old kittens from litter E.\\nKittens from litter D have been moved to the Litters section.', '2015-06-05', NULL),
(124, 'Máme nová koťátka - vrh E', 'We have new kittens - litter E', 'Prohlédněte si první fotografie našich nových koťátek', 'Check out the first photos of our new kittens.', '2015-05-07', NULL),
(125, 'Nové fotografie koťátek z vrhu D', 'New photos of kittens from litter D', 'Prohlédněte si nové fotografie 6-týdenních koťátek z vrhu D', 'Check out the new photos of 6-week-old kittens from litter D.', '2015-04-02', NULL),
(126, 'Máme nová koťátka - vrh D', 'We have new kittens - litter D', 'Představujeme první fotografie našich 3-týdenních koťátek z vrhu D. Brzy se těšte na další :)\\nKoťátka z vrhů B a C byla přesunuta do Odchovů.', 'Introducing the first photos of our 3-week-old kittens from litter D. Look forward to more soon :)\\nKittens from litters B and C have been moved to the Litters section.', '2015-03-17', NULL),
(128, 'Opět přinášíme nové fotografie koťátek z obou aktuálních vrhů', 'Again, we bring new photos of kittens from both current litters', '', '', '2015-01-08', NULL),
(129, 'Nové fotografie koťátek z obou aktuálních vrhů', 'New photos of kittens from both current litters', '', '', '2014-12-29', NULL),
(130, 'Máme nová koťátka', 'We have new kittens', 'Máme nová koťátka ze dvou vrhů B a C. Více informací naleznete v sekci Koťátka.', 'We have new kittens from two litters B and C. More information can be found in the Kittens section.', '2014-12-29', NULL),
(131, 'Poslední volná koťátka z vrhu \"Z\" ihned k odběru', 'Last available kittens from litter \"Z\" ready for pickup', 'Zoly byla na operaci s ouškem, proto má jednu stranu hlavy vyholenou, ale vše dopadlo dobře a Zoly je v pořádku.', 'Zoly had ear surgery, so one side of her head is shaved, but everything turned out well and Zoly is fine.', '2013-11-09', NULL),
(132, 'Nové fotografie koťátek z vrhů \"Z\" a \"A\"', 'New photos of kittens from litters \"Z\" and \"A\"', 'Více podrobností o koťátkách naleznete jako vždy v sekci Koťátka.', 'More details about the kittens can be found as always in the Kittens section.', '2013-09-10', NULL),
(133, 'Aktuální fotografie z obou vrhů \"Z\" a \"A\".', 'Current photos from both litters \"Z\" and \"A\".', '', '', '2013-08-03', NULL),
(134, 'Představujeme nová koťátka z vrhu \"Z\" a \"A\"', 'Introducing new kittens from litters \"Z\" and \"A\"', 'Protože jsme u konce abecedy, začínáme znovu od písmene \"A\" :)', 'Since we are at the end of the alphabet, we are starting again from the letter \"A\" :)', '2013-07-18', NULL),
(135, 'Nové fotografie koťátek z vrhu \"Y\"', 'New photos of kittens from litter \"Y\"', 'Dne 14. 3. 2013 se nám narodili 3 kluci a 2 holčičky ze spojení Ornela Garfield\'s Baby a CH Cleo Wild Rose.', 'On 14.3.2013, 3 boys and 2 girls were born from the pairing of Ornela Garfield\'s Baby and CH Cleo Wild Rose.', '2013-06-13', NULL),
(136, 'První fotografie koťátek z vrhu \"Y\"', 'First photos of kittens from litter \"Y\"', 'Dne 14. 3. 2013 se nám narodili 3 kluci a 2 holčičky ze spojení Ornela Garfield\'s Baby a CH Cleo Wild Rose.', 'On 14.3.2013, 3 boys and 2 girls were born from the pairing of Ornela Garfield\'s Baby and CH Cleo Wild Rose.', '2013-05-16', NULL),
(137, 'Nové fotografie koťátek z vrhů \"W\" a \"X\"', 'New photos of kittens from litters \"W\" and \"X\"', '', '', '2013-04-15', NULL),
(142, 'Shakira Garfield\'s Baby se stala supreme šampionkou!', 'Shakira Garfield\'s Baby became a supreme champion!', 'Děkujeme chovatelské stanici Marman\'s maine coon za fotografii ze soutěže a přejem mnoho úspěchů Vám i dalším chovatelům našich koťátek :)', 'Thank you to the Marman\'s maine coon cattery for the photo from the competition and we wish you and other breeders of our kittens much success :)', '2016-08-19', '../img/news/shakira_champ.jpg, ../img/news/FIFe_Shakira.jpg'),
(143, 'Nové fotografie koťátek - vrh I', 'New photos of kittens - litter I', 'Podívejte se na nové fotografie koťátek z vrhu I, už je jim 10 týdnů :o)\r\nVrh CH přesunut do Odchovů', 'Check out the new photos of kittens from litter I, they are already 10 weeks old :o)\r\nLitter CH has been moved to the Litters section.', '2016-01-09', NULL),
(144, 'Máme nová koťátka - vrh \"Y\"', 'We have new kittens - litter \"Y\"', 'Dne 14.3. se císařským řezem narodili 3 kluci a 2 holky ze spojení Ornela Garfield\'s Baby a CH Cleo Wild Rose. Ornela se o miminka odmítla starat a veškerou péči přenechala s naprostou důvěrou své chovatelce, která již 4 týdny o miminka pečuje. Zatím úspěšně.', 'On 14.3., 3 boys and 2 girls were born by cesarean section from the pairing of Ornela Garfield\'s Baby and CH Cleo Wild Rose. Ornela refused to care for the babies and entrusted all care to her breeder, who has been caring for them for 4 weeks now. So far successfully.', '2013-04-15', NULL),
(145, 'Aktualizována sekce Plán\r\n\r\nDo sekce Kočky byla přidána Rebeka Garfield\'s Baby.', 'Updated Plan section\r\n\r\nRebeka Garfield\'s Baby has been added to the Cats section.', '', '', '2013-04-15', NULL),
(146, 'Nové fotografie koťátek z vrhů \"W\" a \"X\"', 'New photos of kittens from litters \"W\" and \"X\"', '', '', '2013-03-22', NULL),
(147, 'Představujeme koťátka z vrhu \"W\" a \"X\"', 'Introducing kittens from litters \"W\" and \"X\"', '', '', '2013-03-22', NULL),
(148, 'Nové fotografie koťátek - vrh \"U\" a \"V\".', 'New photos of kittens - litters \"U\" and \"V\".', '', '', '2013-01-30', NULL),
(149, 'Máme nová koťátka - vrh \"U\" a \"V\". Podívejte se na jejich první fotografie.', 'We have new kittens - litters \"U\" and \"V\". Check out their first photos.', '', '', '2013-01-04', NULL),
(150, 'Koťátkům z vrhu \"S\" a \"T\" je už 13 týdnů. Podívejte se na jejich fotografie.', 'Kittens from litters \"S\" and \"T\" are already 13 weeks old. Check out their photos.', '', '', '2012-10-27', NULL),
(151, 'Přidány nové fotografie koťátek z vrhu \"S\" a \"T\".', 'New photos of kittens from litters \"S\" and \"T\" have been added.', '', '', '2012-09-28', NULL);
INSERT INTO `news` (`id`, `title`, `title_en`, `content`, `content_en`, `created_at`, `image`) VALUES
(152, 'Představujeme koťátka z vrhu \"S\" a \"T\"', 'Introducing kittens from litters \"S\" and \"T\"', 'Při tragické události během mé nepřítomnosti jsme přišli o 6 koťátek :-(', 'During a tragic event in my absence, we lost 6 kittens :-(', '2012-09-12', NULL),
(153, 'MÁME NOVÁ KOŤÁTKA - VRH \"S\" a \"T\" - první fotografie již brzy na našich stránkách!', 'WE HAVE NEW KITTENS - LITTERS \"S\" AND \"T\" - FIRST PHOTOS COMING SOON TO OUR WEBSITE!', '', '', '2012-07-31', NULL),
(154, 'Očekáváme nová koťátka! Více informací v sekci Plán.', 'We are expecting new kittens! More information in the Plan section.', 'Děkujeme chovatelské stanici Pumelia Garden za nakrytí našich kočiček kocourem Zeusem.', 'Thank you to the Pumelia Garden cattery for breeding our cats with the stud Zeus.', '2012-06-08', NULL),
(155, 'Představujeme odrostlé chovné kočičky Mauglinu, Osiris a Ornelu a nového chovného kocoura Clea.', 'Introducing grown-up breeding cats Mauglina, Osiris, and Ornela and a new breeding stud Cleo.', 'Více informací v sekci Kocouři a Kočky.', 'More information in the Studs and Cats sections.', '2012-06-08', NULL),
(156, 'Nově vytvořená sekce Kastráti.', 'Newly created Castrates section.', '', '', '2012-06-08', NULL),
(157, 'Vrh Q přesunutý do odchovů.', 'Litter Q moved to the Litters section.', '', '', '2012-06-08', NULL),
(158, 'Do odchovů přidán vrh R.', 'Litter R added to the Litters section.', '', '', '2012-06-08', NULL),
(159, 'Queen - poslední volná kočička z vrhu Q', 'Queen - last available kitten from litter Q', 'Poslední volné kočičce z vrhu Q je 17 týdnů. Její aktuální fotografie najdete jako vždy v sekci Koťátka.', 'The last available kitten from litter Q is 17 weeks old. Her current photos can be found as always in the Kittens section.', '2012-03-05', NULL),
(160, 'Dvě volné kočičky z vrhu Q', 'Two available kittens from litter Q', 'Koťátkům z vrhu Q je právě 14 týdnů.', 'The kittens from litter Q are now 14 weeks old.', '2012-02-13', NULL),
(161, 'Přidány nové fotografie koťátek obou aktuálních vrhů \"P\" a \"Q\".', 'New photos of kittens from both current litters \"P\" and \"Q\" have been added.', '', '', '2012-01-20', NULL),
(162, 'Nové fotografie našich obou aktuálních vrhů \"P\" a \"Q\" v sekci Koťátka', 'New photos of our current litters \"P\" and \"Q\" in the Kittens section', '', '', '2011-12-28', NULL),
(163, 'MÁME NOVÁ KOŤÁTKA', 'WE HAVE NEW KITTENS', 'Dva nové vrhy koťátek \"P\" a \"Q\" a jejich první fotografie v sekci Koťátka', 'Two new litters of kittens \"P\" and \"Q\" and their first photos in the Kittens section.', '2011-12-07', NULL),
(164, 'Naggi Garfield\'s Baby - poslední volná kočička z vrhu \"N\"', 'Naggi Garfield\'s Baby - last available kitten from litter \"N\"', 'Už jen jedna volná kočička z vrhu N. Její aktuální fotografie najdete v sekci Koťátka.', 'Only one available kitten left from litter N. Her current photos can be found in the Kittens section.', '2011-11-15', NULL),
(165, 'Nové fotografie všech tří volných koťátek v sekci Koťátka.', 'New photos of all three available kittens in the Kittens section.', '', '', '2011-10-29', NULL),
(166, 'Přidány nové fotografie koťátek z vrhu \"M\" a \"O\".', 'New photos of kittens from litters \"M\" and \"O\" have been added.', '', '', '2011-10-17', NULL),
(167, 'Nové fotografie koťátek z vrhu \"N\" v sekci Koťátka.', 'New photos of kittens from litter \"N\" in the Kittens section.', '', '', '2011-10-09', NULL),
(168, 'Po dvou týdnech přišlo na řadu opět focení koťátek z vrhu \"M\" a \"O\".', 'After two weeks, it\'s time to photograph kittens from litters \"M\" and \"O\" again.', 'Jejich současné fotografie nejdete v sekci Koťátka.', 'Their current photos can be found in the Kittens section.', '2011-10-04', NULL),
(169, 'Opět přidáváme nové fotografie koťátek z vrhu N.', 'Again, we are adding new photos of kittens from litter N.', '', '', '2011-09-26', NULL),
(170, 'Chopper Garfield\'s Baby', 'Chopper Garfield\'s Baby', 'Do sekce Kocouři jsme přidali Choppera Garfiend\'s Baby.\r\nNajdete zde jeho aktuální fotografie včetně rodokmenu.', 'In the Studs section, we have added Chopper Garfiend\'s Baby.\r\nYou can find his current photos including his pedigree.', '2017-02-14', '../img/castrates/chopper_01.jpg'),
(171, 'Představujeme dvě nové chovné kočičky a jednoho krycího kocoura', 'Introducing two new breeding cats and one stud cat', 'Aktuální fotografie obou koček včetně rodokmenu najdete v sekci Kočky.\r\n\r\nNového krycího kocoura v sekci Kocouři', 'Current photos of both cats including their pedigrees can be found in the Cats section.\r\n\r\nNew stud cat in the Studs section.', '2021-02-03', '../img/cats/quella_01.jpg, \n../img/cats/rachel_01.jpg, \n../img/toms/honeydevil_01.jpg'),
(172, 'Představujeme novou chovnou kočičky a dva krycí kocoury', 'Introducing a new breeding cat and two stud cats', 'Aktuální fotografie Angely včetně rodokmenu najdete v sekci Kočky.\r\n\r\nFotografie včetně rodokmenu najdete v sekci Kocouři', 'Current photos of Angela including her pedigree can be found in the Cats section.\r\n\r\nPhotos including pedigrees can be found in the Studs section.', '2021-10-13', '../img/cats/angela_01.jpg,\r\n../img/toms/hope_01.jpg,\r\n../img/toms/mario_01.jpg');

--
-- Indexy pro exportované tabulky
--

--
-- Indexy pro tabulku `news`
--
ALTER TABLE `news`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT pro tabulky
--

--
-- AUTO_INCREMENT pro tabulku `news`
--
ALTER TABLE `news`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=173;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
